### ISSUE TITLE
Mob don't move

### ISSUE THREAD

**Issue by junxiesky** [jasonwynn10/VanillaEntityAI#34] opened 2019-08-30 18:22 UTC
**Describe the bug**
Animal and mob Can't move

**To Reproduce**
1. summon a chicken

**Expected behavior**
Animals can move normally

**Screenshots**
null

**Client Information (please complete the following information):**
 - PocketMine API Version: 3.9.4
 - Plugin Version: 1.0.0-alpha5
 - PHP Version: 7.2.8

**Additional context**
Add any other context about the problem here. Links to your report on https://crash.pmmp.io are helpful!

**Comment by TheWalker0** [comment] 2019-09-08 20:24
true

**Comment by jasonwynn10** [comment] 2019-09-09 11:26
I don't know what you expected from an alpha build. It's nowhere near finished

**Comment by jasonwynn10** [comment] 2019-09-09 11:27
duplicate of #33

**Closed by jasonwynn10** 2019-09-09 11:27 UTC
