### ISSUE TITLE
Instant Crash after changing Level

### ISSUE THREAD

**Issue by SchdowNVIDIA** [jasonwynn10/VanillaEntityAI#16] opened 2019-02-22 15:26 UTC
PocketMine-MP Crash Dump Fri Feb 22 15:24:16 UTC 2019

Error: Undefined offset: 131
File: plugins/VanillaEntityAI-master/src/jasonwynn10/VanillaEntityAI/EntityListener
Line: 41
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: VanillaEntityAI v0.0.1

Code:
[32] 	 * @param ChunkLoadEvent $event
[33] 	 */
[34] 	public function onLoad(ChunkLoadEvent $event) {
[35] 		$chunk = $event->getChunk();
[36] 		$level = $event->getLevel();
[37] 		$packCenter = new Vector3(mt_rand($chunk->getX() << 4, (($chunk->getX() << 4) + 15)), mt_rand(0, $level->getWorldHeight() - 1), mt_rand($chunk->getZ() << 4, (($chunk->getZ() << 4) + 15)));
[38] 		$lightLevel = $level->getFullLightAt($packCenter->x, $packCenter->y, $packCenter->z);
[39] 		if(!$level->getBlockAt($packCenter->x, $packCenter->y, $packCenter->z)->isSolid() and $lightLevel > 8) {
[40] 			$biomeId = $level->getBiomeId($packCenter->x, $packCenter->z);
[41] 			$entityList = BiomeEntityList::BIOME_ANIMALS[$biomeId];
[42] 			if(empty($entityList))
[43] 				return; // no entities for this biome
[44] 			$entityId = $entityList[array_rand(BiomeEntityList::BIOME_ANIMALS[$biomeId])];
[45] 			if(!$level->getBlockAt($packCenter->x, $packCenter->y, $packCenter->z)->isSolid()) {
[46] 				for($attempts = 0, $currentPackSize = 0; $attempts <= 12 and $currentPackSize < 4; $attempts++) {
[47] 					$x = mt_rand(-20, 20) + $packCenter->x;
[48] 					$z = mt_rand(-20, 20) + $packCenter->z;
[49] 					foreach(EntityAI::$entities as $class => $arr) {
[50] 						if($class instanceof AnimalBase and $class::NETWORK_ID === $entityId) {
[51] 							$entity = $class::spawnMob(new Position($x + 0.5, $packCenter->y, $z + 0.5, $level));

Backtrace:
#0 plugins/VanillaEntityAI-master/src/jasonwynn10/VanillaEntityAI/EntityListener(41): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string Undefined offset: 131, string /servers/citybuild-test/plugins/VanillaEntityAI-master/src/jasonwynn10/VanillaEntityAI/EntityListener.php, integer 41, array Array())
#1 src/pocketmine/plugin/MethodEventExecutor(38): jasonwynn10\VanillaEntityAI\EntityListener->onLoad(pocketmine\event\level\ChunkLoadEvent object)
#2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(jasonwynn10\VanillaEntityAI\EntityListener object, pocketmine\event\level\ChunkLoadEvent object)
#3 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\level\ChunkLoadEvent object)
#4 src/pocketmine/level/Level(2830): pocketmine\event\Event->call()
#5 src/pocketmine/level/Level(2401): pocketmine\level\Level->loadChunk(integer 8, integer 10, boolean 1)
#6 src/pocketmine/level/Level(3092): pocketmine\level\Level->getChunk(integer 8, integer 10, boolean 1)
#7 src/pocketmine/Player(1050): pocketmine\level\Level->populateChunk(integer 8, integer 10)
#8 src/pocketmine/Player(1828): pocketmine\Player->sendNextChunk()
#9 src/pocketmine/Server(2601): pocketmine\Player->checkNetwork()
#10 src/pocketmine/Server(2346): pocketmine\Server->tick()
#11 src/pocketmine/Server(2209): pocketmine\Server->tickProcessor()
#12 src/pocketmine/Server(1785): pocketmine\Server->start()
#13 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /servers/citybuild-test/, string /servers/citybuild-test/plugins/)
#14 (1): require(string phar:///servers/citybuild-test/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by jasonwynn10** [comment] 2019-02-22 15:44
duplicate of #13

**Closed by jasonwynn10** 2019-02-22 15:44 UTC
